from os import PathLike
from typing import ContextManager, Sequence, overload

import numpy as np
import numpy.typing as npt

from . import data as data
from . import explain as explain
from . import nn as nn
from . import optim as optim

FloatArray = npt.NDArray[np.float32]
ArrayLike = npt.ArrayLike
Shape = Sequence[int]

class DeviceType:
    CPU: DeviceType
    OPENCL: DeviceType

class KernelProfile:
    operation: str
    calls: int
    total_milliseconds: float
    minimum_milliseconds: float
    maximum_milliseconds: float

class OpenCLRuntimeStatistics:
    buffer_allocations: int
    buffer_reuses: int
    pooled_buffers: int
    cached_kernels: int

class Device:
    @staticmethod
    def cpu() -> Device: ...
    @staticmethod
    def opencl(platform_index: int = ..., device_index: int = ...) -> Device: ...
    @property
    def type(self) -> DeviceType: ...
    @property
    def platform_index(self) -> int: ...
    @property
    def device_index(self) -> int: ...
    @property
    def name(self) -> str: ...
    def synchronize(self) -> None: ...
    def set_profiling(self, enabled: bool) -> None: ...
    def profile(self, reset: bool = ...) -> list[KernelProfile]: ...
    def runtime_statistics(self) -> OpenCLRuntimeStatistics: ...
    def clear_memory_pool(self) -> None: ...

class Tensor:
    def __init__(self, data: ArrayLike, requires_grad: bool = ..., name: str = ...,
                 device: Device = ...) -> None: ...
    @staticmethod
    def scalar(value: float, requires_grad: bool = ..., name: str = ...,
               device: Device = ...) -> Tensor: ...
    @staticmethod
    def zeros(shape: Shape, requires_grad: bool = ..., name: str = ...,
              device: Device = ...) -> Tensor: ...
    @staticmethod
    def ones(shape: Shape, requires_grad: bool = ..., name: str = ...,
             device: Device = ...) -> Tensor: ...
    @staticmethod
    def randn(shape: Shape, mean: float = ..., standard_deviation: float = ...,
              requires_grad: bool = ..., seed: int = ..., name: str = ...,
              device: Device = ...) -> Tensor: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def defined(self) -> bool: ...
    @property
    def is_scalar(self) -> bool: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def requires_grad(self) -> bool: ...
    @property
    def is_leaf(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def device(self) -> Device: ...
    @property
    def grad(self) -> FloatArray | None: ...
    def numpy(self) -> FloatArray: ...
    def item(self) -> float: ...
    def backward(self, gradient: Tensor | None = ..., retain_graph: bool = ...) -> None: ...
    def zero_grad(self) -> None: ...
    def set_data(self, values: ArrayLike) -> None: ...
    def detach(self) -> Tensor: ...
    def to(self, device: Device) -> Tensor: ...
    def reshape(self, shape: Shape) -> Tensor: ...
    def transpose(self) -> Tensor: ...
    @overload
    def sum(self) -> Tensor: ...
    @overload
    def sum(self, dimension: int, keep_dimensions: bool = ...) -> Tensor: ...
    @overload
    def mean(self) -> Tensor: ...
    @overload
    def mean(self, dimension: int, keep_dimensions: bool = ...) -> Tensor: ...
    def __len__(self) -> int: ...
    def __add__(self, other: Tensor | float) -> Tensor: ...
    def __radd__(self, other: float) -> Tensor: ...
    def __sub__(self, other: Tensor | float) -> Tensor: ...
    def __rsub__(self, other: float) -> Tensor: ...
    def __mul__(self, other: Tensor | float) -> Tensor: ...
    def __rmul__(self, other: float) -> Tensor: ...
    def __truediv__(self, other: Tensor | float) -> Tensor: ...
    def __rtruediv__(self, other: float) -> Tensor: ...
    def __neg__(self) -> Tensor: ...

class TensorStatistics:
    minimum: float
    maximum: float
    mean: float
    standard_deviation: float
    l2_norm: float
    non_finite: int

def opencl_available() -> bool: ...
def grad_enabled() -> bool: ...
def no_grad() -> ContextManager[object]: ...
def numel(shape: Shape) -> int: ...
def shape_string(shape: Shape) -> str: ...
def matmul(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def conv2d(input: Tensor, weight: Tensor, bias: Tensor | None = ...,
           stride: tuple[int, int] = ..., padding: tuple[int, int] = ...) -> Tensor: ...
def max_pool2d(input: Tensor, kernel_size: tuple[int, int],
               stride: tuple[int, int] = ..., padding: tuple[int, int] = ...) -> Tensor: ...
def avg_pool2d(input: Tensor, kernel_size: tuple[int, int],
               stride: tuple[int, int] = ..., padding: tuple[int, int] = ...) -> Tensor: ...
@overload
def sum(input: Tensor) -> Tensor: ...
@overload
def sum(input: Tensor, dimension: int, keep_dimensions: bool = ...) -> Tensor: ...
@overload
def mean(input: Tensor) -> Tensor: ...
@overload
def mean(input: Tensor, dimension: int, keep_dimensions: bool = ...) -> Tensor: ...
def pow(input: Tensor, exponent: float) -> Tensor: ...
def exp(input: Tensor) -> Tensor: ...
def log(input: Tensor) -> Tensor: ...
def relu(input: Tensor) -> Tensor: ...
def leaky_relu(input: Tensor, negative_slope: float = ...) -> Tensor: ...
def sigmoid(input: Tensor) -> Tensor: ...
def tanh(input: Tensor) -> Tensor: ...
def softmax(input: Tensor, dimension: int) -> Tensor: ...
def reshape(input: Tensor, shape: Shape) -> Tensor: ...
def transpose(input: Tensor) -> Tensor: ...
def mse_loss(prediction: Tensor, target: Tensor) -> Tensor: ...
def binary_cross_entropy(prediction: Tensor, target: Tensor, epsilon: float = ...) -> Tensor: ...
def binary_cross_entropy_with_logits(logits: Tensor, target: Tensor) -> Tensor: ...
def cross_entropy(logits: Tensor, labels: Sequence[int]) -> Tensor: ...
def statistics(tensor: Tensor) -> TensorStatistics: ...
def inspect(tensor: Tensor, maximum_values: int = ...) -> str: ...

__version__: str
