from os import PathLike
from typing import Iterator, Sequence

import numpy.typing as npt

from . import Device, Tensor

class TensorDataset:
    def __init__(self, inputs: npt.ArrayLike, targets: npt.ArrayLike,
                 class_labels: Sequence[int] | None = ...) -> None: ...
    def __len__(self) -> int: ...
    @property
    def input_shape(self) -> list[int]: ...
    @property
    def target_shape(self) -> list[int]: ...
    @property
    def has_class_labels(self) -> bool: ...
    def subset(self, indices: Sequence[int]) -> TensorDataset: ...

class DatasetSplit:
    training: TensorDataset
    validation: TensorDataset
    test: TensorDataset

class Batch:
    inputs: Tensor
    targets: Tensor
    class_labels: list[int]
    size: int

class DataLoader:
    def __init__(self, dataset: TensorDataset, batch_size: int, device: Device = ...,
                 shuffle: bool = ..., seed: int = ..., drop_last: bool = ...,
                 prefetch: bool = ...) -> None: ...
    def reset(self, seed: int | None = ...) -> None: ...
    @property
    def batch_count(self) -> int: ...
    @property
    def prefetch_enabled(self) -> bool: ...
    def __iter__(self) -> Iterator[Batch]: ...
    def __next__(self) -> Batch: ...

def split(dataset: TensorDataset, training_fraction: float,
          validation_fraction: float, seed: int = ...) -> DatasetSplit: ...
def load_csv_numerical(path: str | PathLike[str], input_columns: Sequence[str],
                       target_columns: Sequence[str], delimiter: str = ...) -> TensorDataset: ...
def load_cifar10_batch(path: str | PathLike[str], normalize: bool = ...) -> TensorDataset: ...
