from os import PathLike
from typing import Callable
from . import Device, Tensor

class ModuleType:
    CUSTOM: ModuleType
    LINEAR: ModuleType
    CONVOLUTION_2D: ModuleType
    RELU: ModuleType
    SIGMOID: ModuleType
    TANH: ModuleType
    FLATTEN: ModuleType
    LEAKY_RELU: ModuleType
    SOFTMAX: ModuleType
    MAX_POOL_2D: ModuleType
    AVERAGE_POOL_2D: ModuleType
    DROPOUT: ModuleType
    BATCH_NORMALIZATION: ModuleType
    LAYER_NORMALIZATION: ModuleType
    GLOBAL_AVERAGE_POOL_2D: ModuleType
    RESIDUAL: ModuleType

class PaddingMode:
    VALID: PaddingMode
    SAME: PaddingMode

class Module:
    def forward(self, input: Tensor) -> Tensor: ...
    def __call__(self, input: Tensor) -> Tensor: ...
    def parameters(self) -> list[Tensor]: ...
    def named_parameters(self) -> dict[str, Tensor]: ...
    def named_buffers(self) -> dict[str, Tensor]: ...
    @property
    def type(self) -> ModuleType: ...
    @property
    def training(self) -> bool: ...
    def to(self, device: Device) -> Module: ...
    def train(self, training: bool = ...) -> Module: ...
    def eval(self) -> Module: ...
    def register_forward_hook(
        self, hook: Callable[[Module, Tensor, Tensor], None]
    ) -> ForwardHookHandle: ...

class ForwardHookHandle:
    @property
    def active(self) -> bool: ...
    def remove(self) -> None: ...

class Linear(Module):
    def __init__(self, input_features: int, output_features: int, bias: bool = ...,
                 seed: int = ..., device: Device = ...) -> None: ...
    @property
    def weight(self) -> Tensor: ...
    @property
    def bias(self) -> Tensor: ...
    @property
    def input_features(self) -> int: ...
    @property
    def output_features(self) -> int: ...
    @property
    def has_bias(self) -> bool: ...

class Conv2d(Module):
    def __init__(self, input_channels: int, output_channels: int,
                 kernel_size: tuple[int, int], stride: tuple[int, int] = ...,
                 padding: str | tuple[int, int] = ..., bias: bool = ...,
                 seed: int = ..., device: Device = ...) -> None: ...
    @property
    def weight(self) -> Tensor: ...
    @property
    def bias(self) -> Tensor: ...
    @property
    def input_channels(self) -> int: ...
    @property
    def output_channels(self) -> int: ...
    @property
    def kernel_size(self) -> tuple[int, int]: ...
    @property
    def stride(self) -> tuple[int, int]: ...
    @property
    def padding(self) -> tuple[int, int]: ...
    @property
    def has_bias(self) -> bool: ...

class ReLU(Module): ...
class Sigmoid(Module): ...
class Tanh(Module): ...
class Flatten(Module): ...

class LeakyReLU(Module):
    def __init__(self, negative_slope: float = ...) -> None: ...
    @property
    def negative_slope(self) -> float: ...

class Softmax(Module):
    def __init__(self, dimension: int = ...) -> None: ...
    @property
    def dimension(self) -> int: ...

class MaxPool2d(Module):
    def __init__(self, kernel_size: tuple[int, int], stride: tuple[int, int] = ...,
                 padding: tuple[int, int] = ...) -> None: ...
    @property
    def kernel_size(self) -> tuple[int, int]: ...
    @property
    def stride(self) -> tuple[int, int]: ...
    @property
    def padding(self) -> tuple[int, int]: ...

class AvgPool2d(Module):
    def __init__(self, kernel_size: tuple[int, int], stride: tuple[int, int] = ...,
                 padding: tuple[int, int] = ...) -> None: ...
    @property
    def kernel_size(self) -> tuple[int, int]: ...
    @property
    def stride(self) -> tuple[int, int]: ...
    @property
    def padding(self) -> tuple[int, int]: ...

class Dropout(Module):
    def __init__(self, probability: float = ..., seed: int = ...) -> None: ...
    @property
    def probability(self) -> float: ...

class BatchNorm(Module):
    def __init__(self, features: int, epsilon: float = ..., momentum: float = ...,
                 affine: bool = ..., device: Device = ...) -> None: ...
    @property
    def features(self) -> int: ...
    @property
    def epsilon(self) -> float: ...
    @property
    def momentum(self) -> float: ...
    @property
    def affine(self) -> bool: ...
    @property
    def weight(self) -> Tensor: ...
    @property
    def bias(self) -> Tensor: ...
    @property
    def running_mean(self) -> Tensor: ...
    @property
    def running_variance(self) -> Tensor: ...

class LayerNorm(Module):
    def __init__(self, normalized_shape: list[int], epsilon: float = ...,
                 affine: bool = ..., device: Device = ...) -> None: ...
    @property
    def normalized_shape(self) -> list[int]: ...
    @property
    def epsilon(self) -> float: ...
    @property
    def affine(self) -> bool: ...
    @property
    def weight(self) -> Tensor: ...
    @property
    def bias(self) -> Tensor: ...

class GlobalAvgPool2d(Module): ...

class Residual(Module):
    def __init__(self, module: Module) -> None: ...
    @property
    def module(self) -> Module: ...

class Sequential(Module):
    def __init__(self) -> None: ...
    def add(self, module: Module) -> Sequential: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Module: ...

def save_state_dict(module: Module, path: str | PathLike[str]) -> None: ...
def load_state_dict(module: Module, path: str | PathLike[str]) -> None: ...
def save_checkpoint(model: Sequential, path: str | PathLike[str]) -> None: ...
def load_checkpoint(path: str | PathLike[str], device: Device = ...,
                    initialization_seed: int = ...) -> Sequential: ...
